### ISSUE TITLE
Possible code refactorings

### ISSUE THREAD

**Issue by willpinha** [HTsuyoshi/flashcards-cli#1]
- Rename `Game_mode` enum to `Mode`
- Rename `Icons` enum to `Icon`
- Rename `Algorithms` enum to `Algorithm`
- Rename `GameLogic` to `Logic`
- Rename `GameScreen` to `Screen`
- Wrap `Mode`, `Icon`, `Algorithm`, `Logic` and `Screen` in a game module separate from the main `flashcards.py` file

If you want, I can make a pull request with the above refactorings.

**Comment by HTsuyoshi** [comment]
Feel free to make these changes!
I would appreciate it! :D
