### ISSUE TITLE
Problems with Python `v3.8.10`

### ISSUE THREAD

**Issue by willpinha** [HTsuyoshi/flashcards-cli#2]
Apparently, some syntaxes used in the code do not match python versions less than or equal to 3.8.10.

The problem lies in the notations in the form `def function(...) -> type[...]`, which return the error `'type' object is not subscriptable`, indicating that the interpreter does not support `type[...]` and interprets it as an access to an index.

An example occurs in the line 129:
```diff
  @classmethod
- def get_window_size(cls) -> tuple[int, int]:
    return (int(os.get_terminal_size().columns), int(os.get_terminal_size().lines))
```

> 💡 The problem can be solved with `from __future__ import annotations`

What version is being used to run the code?

**Comment by HTsuyoshi** [comment]
Hmm, thats interesting. I'll add this line of code! Thanks!

```python
from __future__ import annotations
```

> What version is being used to run the code?

Yeah, I think this is another problem. I setup the `Dockerfile` to get the lastest python version (Now I think its `3.10.7`). I'll change it to get a specific version, so the problem won't happen again.

**Comment by willpinha** [comment]
The docker settings are not the problem as I ran the script locally! I think `from __future__ import annnotations` are enough for the script to support older versions of python.
